### ISSUE TITLE
Battery percentage never reads 100%

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#103]
Need to lower the voltage value that is used as  the 100% value

**Comment by f1rmb** [comment]
I also have this problem, on a 15 days old handheld (needed to hack the code to check the new batt icon ;-) ).

**Comment by rogerclarkmelbourne** [comment]
Reduced MAX battery voltage define from 83 to 82 (8.3 to 8.2V)

7c4e4f57881c6f9e0d1bd42db7974db7bcd26c06

**Comment by rogerclarkmelbourne** [comment]
I don't think we can every guarantee that all radios will reach 100% charge
