### ISSUE TITLE
Incorrect TA data for some stations

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#110]
![Picture 194](https://user-images.githubusercontent.com/6146984/69215168-07742c80-0bbd-11ea-9ef8-8f3b394e8377.jpg)

**Comment by f1rmb** [comment]
Exaclty what I had yesterday evening this "minus" something...
But dumping MMDVMVHost log file confirmed that was right (and the value on the question mark position are 0x04, IIRC.

**Comment by f1rmb** [comment]
But what is that A/B at the end ?

**Comment by rogerclarkmelbourne** [comment]
I don't know

I presume its in the font ??

**Comment by f1rmb** [comment]
Nope

**Comment by f1rmb** [comment]
I will PR a small change in space removal code (stupid me), but this A/B in are both from the 8x8 font.

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by f1rmb** [comment]
Was it KD5ILG ?

**Comment by rogerclarkmelbourne** [comment]
Sorry. I don't know

It was on TG91 about 20 mins ago. I should have listened for their callsign

**Comment by f1rmb** [comment]
Okay.

**Comment by rogerclarkmelbourne** [comment]
They are not active now on 91

I was busy fixing the scan crash bug

**Comment by f1rmb** [comment]
Yeah, it's quite calm, I can even check if the new callsign extractor from TA works :-D

**Comment by rogerclarkmelbourne** [comment]
(LOL)

Its what's known as "sods law"

**Comment by rogerclarkmelbourne** [comment]
Fixed by e0c0fcb2c294b165e3652d5545a7eabcebb22b5d
