### ISSUE TITLE
Add 50mW and 5W+ power settings

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#117]

**Comment by IW2FHM** [comment]
50 mW or less would be useful for hotspot  use

**Comment by rogerclarkmelbourne** [comment]
This is now in the master source, however the 50mW setting is not reliable on all radios

It may not be possible to implement the 50mW setting because the only calibration points are for 1W and 5W, and the power curve is not linear below 1W, which makes it difficult (or perhaps impossible) to accurately calculate the PA drive needed for 50mW.

**Comment by rogerclarkmelbourne** [comment]
Done
