### ISSUE TITLE
Add DCS squelch support

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#119]

**Comment by ajorg** [comment]
You can assign this to me. I'm maybe 80% done and finding a little time here and there to finish it.

**Comment by ajorg** [comment]
Submitted a PR here: https://github.com/rogerclarkmelbourne/OpenGD77/pull/584

**Comment by rogerclarkmelbourne** [comment]
Thanks. All feedback was positive, so this has now been included in the release on 3rd May
