### ISSUE TITLE
Keypad stops responding

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#145]
I've started to noticed that the keypad sometimes stops responding

This has happened to me after I copied a channel to the VFO, and also when closing the Credits screen, by pressing the Red menu key

It doesn't always stop responding but its definitely happening quite a lot.

There was a report on the forum, from someone who said they had to downgrade from the "latest"version to the stable version because their keypad locked up.

But I'm surprised the problem was not fixed just by rebooting. (To be confirmed)

**Comment by footloosejava** [comment]
>It doesn't always stop responding but its definitely happening quite a lot.
Had this while skiing today. Restart didn't solve it. So I assume it was loose connection/cold/condensation. But it happened in the warm car later tonight and that makes me think loose connection or maybe even bug (now that I read your post above).
I did have some weird pauses in the UI functions yesterday and today when in Scan and maybe some other time.
