### ISSUE TITLE
In All channel zone key UP is only working with english language setting

### ISSUE THREAD

**Issue by alexernst** [rogerclarkmelbourne/OpenGD77#159]

**Comment by rogerclarkmelbourne** [comment]
OK
I will fix

**Comment by rogerclarkmelbourne** [comment]
Can you pull and test.

**Comment by alexernst** [comment]
That works.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I tested in english and french and both seemed to work

BTW. Is there a new way to handle the buttons, or is it just the keys ??

**Comment by alexernst** [comment]
At the moment it's only for keys. But it would be easy to include SK1 and ORANGE into the same functions. That would enable at least short and long detection. I think repeat must be filtered.

PTT has to be handled completely  different and SK2 is also special.

**Comment by rogerclarkmelbourne** [comment]
OK.

BTW. 
I added a hidden feature of SK_1 + SK_2 pressed at the same time saves the current settings, as when developing it is useful to be able to save the settings before uploading via the debugger,

**Comment by alexernst** [comment]
Yes, I already realized that the settings are not saved, since I work with the JLink. The power off in fw_main is never running. 
Perhaps we should  add something like a Debug menu for some 'special' things like saving settings or enable hotspot mode.

**Comment by rogerclarkmelbourne** [comment]
Jlink just halts the process then causes some sort of reset.


We could add something to another menu, but pressing SK_1 and SK_2 works to save the settings if I remember I need to save them.
