### ISSUE TITLE
Difficult to unlock the PTT

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#167]
When PTT is locked and the keypad is not locked then Function + STAR does not unlock the PTT, it switches modes.

Even though this uses up a key combination, perhaps its best to change the PTT unlock to be Function + # to match how you lock the PTT using #

**Comment by f1rmb** [comment]
Ahhh, I see it now, didn't noticed... Doh!

Shall I fix this, with <BLUE>-# as told on the forum ?

**Comment by rogerclarkmelbourne** [comment]
Wait to see what the forum says, but I expect that will be the final decision.

**Comment by rogerclarkmelbourne** [comment]
I think this has been fixed (by Daniel)
