### ISSUE TITLE
VHF-DMR repeater wake up not possible

### ISSUE THREAD

**Issue by DL7DW** [rogerclarkmelbourne/OpenGD77#173]
Radio keeps pinging the repeater but no wake up. Tested on a commercial Hytera RD625 repeater in DMR+ network.

**Comment by rogerclarkmelbourne** [comment]
This is a known issue, which seems to be some problem with Tx calibration

Can you hear traffic on the repeater ?

Is it just the wakeup thats not working or any transmission into the repeater

**Comment by DL7DW** [comment]
It's possible to hear the traffic. Seems to be just the wake up. The native firmware works. I don't know which version but one of the early open GD77-tier2 firmwares worked as well.

**Comment by rogerclarkmelbourne** [comment]
Probably fixed by changes to the calibration lookup changes.

Please re-open if the problem still exists
