### ISSUE TITLE
Possibly add warning screen when reading VFO into channel

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#182]
I've had reports that people don't realise that when the VFO is copied into the Channel its a permanent change.

We may need to add a warning screen, like for the Contacts deletion etc

**Comment by rogerclarkmelbourne** [comment]
I'm closing all enhancement issues

**Comment by rogerclarkmelbourne** [comment]
I'm not sure if this is still a valid issue, so I'm re-opening it

**Comment by da3020** [comment]
Really, it generates very unpleasant situations, when warning is absent.

**Comment by f1rmb** [comment]
This one has been implemented.

**Comment by rogerclarkmelbourne** [comment]
Thanks
