### ISSUE TITLE
Scan immediately reboots on latest firmware 77e763b

### ISSUE THREAD

**Issue by footloosejava** [rogerclarkmelbourne/OpenGD77#202]
Scan immediately reboots on latest firmware 77e763b.
Orange button > Scan > Green key
starts scan, immediately crashes.

**Comment by rogerclarkmelbourne** [comment]
It looks like Daniels changes to use a structure to pass the events rather than separate variable may be causing this.

if I go back to 

f59417363c967c2b0591c7f3288c466c40753314

Which is just prior to that code, the scan is OK.

I'll need to debug it

**Comment by rogerclarkmelbourne** [comment]
Should be fixed by 265006c50e39ea947ee3018e23dc46852647ad90

I'll close this.  Please reopen if the bug persists
