### ISSUE TITLE
VFO button press

### ISSUE THREAD

**Issue by riku2015** [rogerclarkmelbourne/OpenGD77#204]
while press button on vfo mode (press and hold) sound will come but screen is not upgrading frequency.
to replicate, go vfo mode and press and hold up or down. only when key up the frequency will update on screen.

this is more like enhancement than a bug.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

This is a bug. The display should be able to update.

I will fix it

**Comment by rogerclarkmelbourne** [comment]
I have pushed a fix for this, and it will be in the next release.

You can pull and re-test  if you like

**Comment by riku2015** [comment]
thanks, pulled and recompiled, it seems to be working good now. :)
