### ISSUE TITLE
Private call accept system should be made into a separate screen

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#208]
I think it may be better to make the Private Call except display into its own screen, as it would be easier to handle the events and keep the screen in place until the operator has decided whether to accept or decline the Private Call

**Comment by f1rmb** [comment]
Yes, that way it can even stick on screen forever.

**Comment by rogerclarkmelbourne** [comment]
Yes.

I think it should stick on the screen.

And if that is a problem, we can make a setting which controls the Private call behavior.

**Comment by rogerclarkmelbourne** [comment]
Done. By Alex
