### ISSUE TITLE
DTMF tone is stuck until PTT is released.

### ISSUE THREAD

**Issue by f1rmb** [rogerclarkmelbourne/OpenGD77#234]
I think this regression is due to last key event modification made yesterday.
I will fix that ASAP.

**Comment by rogerclarkmelbourne** [comment]
OK

Thanks

I'll post to the forum

**Comment by f1rmb** [comment]
Fix is in PR #235  ;-)

**Comment by alexernst** [comment]
There is always one function not checked...

**Comment by f1rmb** [comment]
Which one ?

**Comment by alexernst** [comment]
I meant I tested a lot but missed to send DTMF after changing the key events.

**Comment by f1rmb** [comment]
Ahhh, okay. No problem,
I won't say a word about that, I'm a winner in that field ;-)
