### ISSUE TITLE
PTT lock is buggy

### ISSUE THREAD

**Issue by f1rmb** [rogerclarkmelbourne/OpenGD77#262]
I noticed that 1 hour ago. I'm currently fixing this.

**Comment by rogerclarkmelbourne** [comment]
OK.

I did not notice, because I have not used this feature yet.

**Comment by f1rmb** [comment]
I guess I won't have enough time tonight to finish that, one little problem still need to be fixed, otherwise it's fine now, no more need to trigger lock screen before unlocking when PTT is locked alone.

**Comment by rogerclarkmelbourne** [comment]
I think this is now fixed
