### ISSUE TITLE
Tx screen is not removed when PTT is released if Tx to repeater fails wake up the repeater

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#272]
Select a non simplex frequency.

Press and then release the PTT and the Tx screen will not exit.

The problem seems to be slightly intermittent

Eventually, it looks like the Tx Timeout may occur and the screen will close.

**Comment by alexernst** [comment]
I will take a look at this.

**Comment by rogerclarkmelbourne** [comment]
Thanks

Its a bit intermittent.

I noticed this when I was accidentally on the wrong frequency this morning.

But when I test it now, the problem has vanished.

**Comment by alexernst** [comment]
In commit #c1c67de he added some changes in lines 134ff in uiTxScreen.c.
Now if <code>trxIsTransmitting == false</code> handleEvent() is only called every 200 ticks. But in DMR mode handleEvent() checks for <code>slot_state<DMR_STATE_TX_START_1</code>. And only then the screen is removed.

But I don't know what Daniel wants to achieve here.
So this one goes to Daniel.

**Comment by f1rmb** [comment]
Hi,

   I wanted to limit jumping into handleEvent() (as everywhere else in menu/ui system).
So I've added condition checking for that, but it seems I missed failure ones.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
OK.

That would make the screen removal dependent on timing between when the PTT was released and whether the DMR was sending the Wake-up pulse or waiting for the response to the Wake-up

**Comment by f1rmb** [comment]
Yup.

   In the PR I've raised, handleEvent won't wait for that if PTT is released.

Cheers.

**Comment by rogerclarkmelbourne** [comment]
Fixed
