### ISSUE TITLE
Zone Issue

### ISSUE THREAD

**Issue by na7q** [rogerclarkmelbourne/OpenGD77#315]
I present you with a zone bug issue of "infinite" spaces.
The radio is loaded with my stock codeplug and stock firmware. I then flash the OpenGD77 firmware. All is well. I then read the radio from the OpenGD77 CPS. I make no changes to the codeplug, I upload as-is, the zone issue is then present and reproduced every time.

At one point it also "latched" on to making a TG contact as a zone and getting stuck in this zone. That issue was unusual and I'm unable to reproduce it, but I think it's semi-related to this issue.

Note the space above All Channels. It goes forever as far as I can say. If you keep going up or down after valid zones, it's just continually blank.
![opengd77bug](https://user-images.githubusercontent.com/1294292/71608258-bc8ef280-2b34-11ea-87d0-e08c53f6d276.png)

To resolve the issue you must completely go back to stock, and reflash the stock based codeplug. I was unable to get it to work otherwise.

If necessary I can upload my codeplug.

**Comment by rogerclarkmelbourne** [comment]
Post your code plug
