### ISSUE TITLE
Show LED when any signal is active

### ISSUE THREAD

**Issue by na7q** [rogerclarkmelbourne/OpenGD77#328]
A huge recommendation for the DMR side of things is having the LED show ANY active signal on the selected frequency. Currently if a signal doesn't match the color code programmed to the memory channel, the LED will not light up. 

I had a minor programming error on a channel, and I couldn't figure out why the radio wasn't receiving a signal, or at least why it appeared that way. It was receiving a signal, I just had the wrong color code. This led to some confusion at first.

**Comment by rogerclarkmelbourne** [comment]
Closing as this in the current experimental release and will be in the next formal 'latest' release
