### ISSUE TITLE
Channels initial TG is not the one programmed in channel

### ISSUE THREAD

**Issue by lb5va** [rogerclarkmelbourne/OpenGD77#386]
Hello.
I'm new to this firmware, downloaded today 19/1-20, stable version.
The first thing that I find strange is that when a channel is selected, the TX talkgroup is NOT the one programmed in the channel. It is an other TG from the RX-list used for that channel. And if an other TG is selcted with the side-arrows, it stays on that TG when changing channel if the channel has the same RX-list, and TS. This is not good!
I cannot read anything in the manual about this and think it might be a bug. 
Is it supposed to be this way?
(I used codeplug from old original fw.)
73s
Stig, LB5VA

**Comment by rogerclarkmelbourne** [comment]
This is by design

All support on how to use the firmware etc is via www.opengd77.com
