### ISSUE TITLE
document the difference between the firmware binaries

### ISSUE THREAD

**Issue by ZeroChaos-** [rogerclarkmelbourne/OpenGD77#397]
Please document the difference between the (currently 3) files in the https://github.com/rogerclarkmelbourne/OpenGD77/tree/master/firmware_binaries/daily_builds folder.  I want to test hotspot tier 1 (and/or tier 2 mode when ready) but I'm not sure the difference between these three files so I don't know which to test.

**Comment by rogerclarkmelbourne** [comment]
https://www.opengd77.com/viewtopic.php?f=5&t=71
