### ISSUE TITLE
Setting the Contact option to "None" in a DMR channel does not work

### ISSUE THREAD

**Issue by jacopo-j** [rogerclarkmelbourne/OpenGD77#427]
Hello. The issue occurs when I create a DMR channel (using the community CPS) and leave the "Contact" option to "None":

![](https://user-images.githubusercontent.com/9914547/74092105-0cf85900-4ac0-11ea-994d-fc18ac9e3f71.png)

According to the help text,

> Selecting the None option prevents a call from being initiated on the channel.

However, what actually happens on the radio is that the first contact from the Contacts list is associated to the channel:

<img src="https://user-images.githubusercontent.com/9914547/74092175-d969fe80-4ac0-11ea-9f51-af8b81a1556e.jpeg" height="500">

and nothing prevents me from initiatiating a call.

**Comment by f1rmb** [comment]
I would check "Rx Only" instead.

Cheers.

**Comment by jacopo-j** [comment]
@f1rmb That does prevent me from making a call. However, my contact #1 is still shown on the cannel's screen, and I feel like it's not supposed to. Is this the intended behaviour?

**Comment by rogerclarkmelbourne** [comment]
This is the intended behaviour 

The digital contract field is not used unless the Rx Group list is set to none.

The Rx Group list data is now used as a list of talk groups associated with the channel, it’s no longer used as the Rx Group list.

Did you read the documentation ?

**Comment by rogerclarkmelbourne** [comment]
Edit.

You can’t set both the contact and Rx group list to none.

It’s not valid for a digital channel not to have a TG.

**Comment by jacopo-j** [comment]
Okay then, I will close this. Thank you.
