### ISSUE TITLE
Capability of using different frequencies on the GD77 when configured as Hotspot (Tx and Rx not the same).

### ISSUE THREAD

**Issue by ecolive19** [rogerclarkmelbourne/OpenGD77#428]
ENHANCEMENT:     It would be great whether we could select the hotspot frequencies on the GD77 configured as hotspot with the OPENGD77 to be not the same... Ta and Ra 5MHz apart or so. Is that possible based on the HW characteristics?
Thanks.

**Comment by rogerclarkmelbourne** [comment]
MMDVMHost totally controls the hotspot. If you want to select different Tx and Rx frequencies, just change them in the MMDVM config file
