### ISSUE TITLE
Talk Permit Tone?

### ISSUE THREAD

**Issue by G0FHM** [rogerclarkmelbourne/OpenGD77#452]
Would it be possible to have it back please? (assuming it's an easy enough job to implement!) Using a RT91 amp when mobile. Radio/Amp is out of visual range when driving. Audible confirmation that I have the repeater would be nice.

Thanks

**Comment by rogerclarkmelbourne** [comment]
You mean this ??

https://www.opengd77.com/viewtopic.php?f=13&t=686

**Comment by G0FHM** [comment]
Er, yes!

Thank you

**Comment by testbird** [comment]
> I tried gettings the radio to receive on the alternate timeslot to the one it was transmitting on, but I was getting some strange effects on the DMR audio when I did this, which is a shame as it would have allowed us to monitor whether the repeater was still transmitting.

Oh yes, that would be cool. Figuring out enough of the DMR chip register configuration of the memory written and read might even allow to confirm that it's exactly the own data frames coming back from the repeater. (Talk permit tone if transmission is confirmed.)

And likewise it could also allow, to re-transmit any frames received on a [auto-start SFR mode channel](https://github.com/hamdv/OpenGD77/issues/57#issuecomment-573774154). :-)

**Comment by rogerclarkmelbourne** [comment]
Closing as Tx Permit has already been released as an experimental build
