### ISSUE TITLE
Store and display the time rececived and the TG in the LastHeard data

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#49]
It may be useful to store the time when the call was received and which TalkGroup, and possibly which Timeslot, in the LastHeard data.

The time would just be relative to when the radio was booted

On the LastHeard screen, additional information could be viewed by selecting item in question.

**Comment by lelkluk** [comment]
I agree, this would be a very nice improvement.
May I suggest that when pressing the green button, the "last heard" item would be just over "zone", between "zone" and "credits". It would be easier to access this useful and current feature
Luc83

**Comment by f1rmb** [comment]
I think this one could be closed.
