### ISSUE TITLE
TX power *-

### ISSUE THREAD

**Issue by bv3un** [rogerclarkmelbourne/OpenGD77#497]

**Comment by bv3un** [comment]
The transmit power setting in each channel is invalid . it will overwrite by Function + Right(Left)
that means you need to set every time after change channel
for example 
using 500mw at home for MMDVM channel and need to 5W for repeater channel outside

**Comment by N4NQY** [comment]
Power seems to default to 1w (at least on my GD-77) and cannot be changed.  Power set in CPS ignored.

**Comment by rogerclarkmelbourne** [comment]
This is by design

The Power setting per channel is ignored, because the codeplug data only has 2 levels, whereas the firmware supports 10 levels

**Comment by bv3un** [comment]
Thanks for answer,so I need to set power every time after change channel Right ?Thanks

傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2020 年 3月 月 23 日週一，時間：12:15 ， Roger Clark <notifications@github.com> 寫道：   


This is by design

The Power setting per channel is ignored, because the codeplug data only has 2 levels, whereas the firmware supports 10 levels

**Comment by rogerclarkmelbourne** [comment]
Yes. If you need a different power for each channel.

Its impossible to support 10 power levels with the CPS format. Hence per channel power setting will never be supported while the official codeplug format is used.

The power level dropdown menu will eventually be removed from the OpenGD77 CPS, but at the moment I have higher priorities

**Comment by bv3un** [comment]
Got itThanks

傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2020 年 3月 月 23 日週一，時間：12:32 ， Roger Clark <notifications@github.com> 寫道：   


Yes. If you need a different power for each channel.

Its impossible to support 10 power levels with the CPS format. Hence per channel power setting will never be supported while the official codeplug format is used.

The power level dropdown menu will eventually be removed from the OpenGD77 CPS, but at the moment I have higher priorities

**Comment by N4NQY** [comment]
Would it be possible to support at least a High and Low setting. Any other choice could be done by Function Right. 

Mostly the High (whatever that may be) Is a good choice but Not wanted when you go to use the radio with a hotspot at home or in a vehicle. 

I agree that there are others ways to accomplish this however, so it’s not a “must”. 

73

jb  N4NQY

**Comment by mti-sk** [comment]
Hi, 
It is possible to set the power for HOTSPOT mode, but only before entering this mode. standard procedure Fn2 button + left or right arrow.
from 50mW-250mW-500mW-750mW-1W-2W-3W-4W-5W

However, the problem is, as I mention in my issue https://github.com/rogerclarkmelbourne/OpenGD77/issues/688 ,
that it is probably not possible to use a power greater than 250mW, because the HOTSPOT mode is terminated spontaneously.

**Comment by f1rmb** [comment]
No, how to define the hotspot power setting is described in the user guide. 

Please, don't add posts to closed issues.
