### ISSUE TITLE
Rename project to more generic name

### ISSUE THREAD

**Issue by consi** [rogerclarkmelbourne/OpenGD77#502]
Hey,

I was wondering, if name of this project shouldn't be changed for example for OpenDMR, LibreDMR or something that will be not bound with specific radio name (similar change was done with XBMC (Xbox Media Center) to Kodi when they moved from Xbox to other platforms)

I could help with refactoring changes in code and .md files to remove old name

**Comment by rogerclarkmelbourne** [comment]
This firmware only runs on the GD-77 and GD-77 Clone (Baofeng DM-1801) 

The master project https://github.com/hamdv  owned by Kai DG4KLU
Any other derivations would most likely be separate projects in different repos under Kai's account.

But other derivations are unlikely to happen, as there are no devs on other hardware platforms who are interested in porting this.
