### ISSUE TITLE
Frequency step should be 6.25 kHz not 6.5 kHz

### ISSUE THREAD

**Issue by alexernst** [rogerclarkmelbourne/OpenGD77#54]
In the CPS you can enter offset step 6.25 in VFO mode, but OpenGD77 uses 6.5.
Also in channels details screen the offset used is 6.5.

Frequency resolution of the AT1846S is 0.0625 kHz. 

In fw_codeplug.c the frequencies are divided by 10. So the last digit is omitted.
The codeplug contains e.g. 446.00625 MHz but in struct_codeplugChannel_t we save 4460062.

**Comment by alexernst** [comment]
I'll prepare a pull request tomorrow.

**Comment by rogerclarkmelbourne** [comment]
Thanks

This may explain why some people report problems with Rx, because the frequency will be wrong by 2.5kHz

**Comment by rogerclarkmelbourne** [comment]
Fixed
