### ISSUE TITLE
Select a File & Update" is not active if model specified in CLI

### ISSUE THREAD

**Issue by deviousway** [rogerclarkmelbourne/OpenGD77#595]
If you run mono FirmwareLoader-Linux.exe with model, for example 

```
mono FirmwareLoader-Linux.exe   DM-1801
```

radio button will active on correct model but buttons "Download and Update" and "Select a File & Update" is not active, to make it active need to switch radio button to any other model.

**Comment by f1rmb** [comment]
Thanks, fix in #588
