### ISSUE TITLE
v0.0.6

### ISSUE THREAD

**Issue by s54ffranc** [rogerclarkmelbourne/OpenGD77#608]

**Comment by s54ffranc** [comment]
Rabim v0.0.6 za gd77. Nikjer je ne najdem.
73de Franc

**Comment by rogerclarkmelbourne** [comment]
There is no version 0.0.6
See https://github.com/rogerclarkmelbourne/Radioddity_GD-77/tree/master/firmware

**Comment by s54ffranc** [comment]
Thanks for the reply. I am looking for 0penGD77 v0.3.5 Sep.14.2019 for BlueDV android hotspot.
73 de Franc

**Comment by rogerclarkmelbourne** [comment]
Why

**Comment by rogerclarkmelbourne** [comment]
FYI.

I presume your read the User Guide. 

Specifically 

https://github.com/rogerclarkmelbourne/OpenGD77/blob/master/docs/OpenGD77_User_Guide.md#hotspot

**Comment by s54ffranc** [comment]
Thanks. I downloaded the latest version.
Greetings
