### ISSUE TITLE
Promiscuous Mode over both Timeslots.

### ISSUE THREAD

**Issue by DL7PJ** [rogerclarkmelbourne/OpenGD77#61]
in the old firmware I always have promiscuous mode over both timeslots. With OpenGD-77, I only see the LED green light but no audio from the other timeslot.

**Comment by rogerclarkmelbourne** [comment]
With Tier2 you must select a TS.

Please propose how the UI to support this

**Comment by DL7PJ** [comment]
the old FW has dual VFO. My setup was VFO1 TS 1 and VFO2 TS2 and my hotspot is sending TS: 1 TG262112 + TS1 TG26322 and TS2: TG2625 + TG26256. So I was able to monitor 4 Talk Groups

**Comment by DL7PJ** [comment]
example photo for two timeslots :
![image](https://user-images.githubusercontent.com/46009291/68798433-b7461900-0656-11ea-9d5c-03a18511786b.png)

**Comment by dc7jzb** [comment]
PJ, now I know what you mean. 8)

Roger, he has worked with the double wait function in the stock Firmware, so the Radio was Jumping between VFO A and B. And on A he had one TS on B the other.
So I think you can take this as a feature request for a Dual Watch function. ;)

**Comment by DL7PJ** [comment]
thank you Mario, that's exactly what I meant and miss in the OPENGD77 FW
Roger that would be optimal. Thank you for the great FW and great work

**Comment by rogerclarkmelbourne** [comment]
Its on the To Do list as part of the general DMR Filtering

I'll should open another topic on the forum as currently its under the Dual Watch thread

http://opengd77.com/viewtopic.php?f=4&t=4

**Comment by rogerclarkmelbourne** [comment]
This has now been implemented

**Comment by DL7PJ** [comment]
Hi Roger , I have tested, great job works very fine and switching is very easy , this is exactly my wish , thanks and 73 Peter 
--
Gesendet über myMail für Android Mittwoch, 27 November 2019, 08:08vorm. +01:00 von Roger Clark  notifications@github.com :

**Comment by rogerclarkmelbourne** [comment]
No worries....
