### ISSUE TITLE
RD-5R talk group memory location possibly wrong.

### ISSUE THREAD

**Issue by Jahnkeanater** [rogerclarkmelbourne/OpenGD77#614]
After flashing the newest development build  f508aa8 from stock firmware the talkgroups became corrupt. I did a factory reset and flashed an empty code plug and there is still 1 old talkgroup and 2 blank talk groups with no tittles.

Seems like the radio reads more memory at the beginning of the list than CPS. You also cannot delete the talkgroup on the radio.

Factory reset does not seem to erase the codeplugs properly.

**Comment by rogerclarkmelbourne** [comment]
The stock codeplug  format is not 100% compatible with this firmware.

Use the tools here to save the RD-5R codeplug to CSV and then import them into a OpenGD77 compatible codeplug.

http://www.gb3gf.co.uk/downloads.html

I'll update the User Guide to highlight this.

**Comment by rogerclarkmelbourne** [comment]
User guide has been updated

**Comment by Jahnkeanater** [comment]
How do I delete the corrupt code plug that is not shown in CPS?

**Comment by rogerclarkmelbourne** [comment]
Github issues are not a support forum

Use https://www.opengd77.com

**Comment by Jahnkeanater** [comment]
After a factory reset and after flashing a blank codeplug using CPS should that not erase all talkgroups?

Also does the delete function in the menu just not work yet?

**Comment by rogerclarkmelbourne** [comment]
Github issues are not a support forum

Use https://www.opengd77.com
