### ISSUE TITLE
RD-5R - Sound configuration is reset every power cycle

### ISSUE THREAD

**Issue by EkosFox** [rogerclarkmelbourne/OpenGD77#648]
Sorry if is duplicate.
If I disable Prompt beep, after turning the radio off and on again it doesn't remember the configuration.

Replicate:
* Go to Menu > Sound options. 
* Turn Prompt to "Silent" and click Menu button to confirm
* Turn off HT
* Turn HT back on
* The option is back at stock

**Comment by rogerclarkmelbourne** [comment]
Can't replicate

**Comment by rogerclarkmelbourne** [comment]
Closed because bug can't be replicated and OP did not respond

**Comment by gigawatts** [comment]
@rogerclarkmelbourne I can confirm that following @EkosFox steps does indeed cause the prompt option to restore to "Beep".

**Comment by rogerclarkmelbourne** [comment]
Try the development version. A similar bug was fixed last week

**Comment by gigawatts** [comment]
Sure, I can give it a shot, you are referring to the June 28th "pre-release" ?
Tag: D2020.06.28  Hash: fed4a21

**Comment by rogerclarkmelbourne** [comment]
Yes. It fixed on sound related problem
