### ISSUE TITLE
Saving New Digital Contact will only accept 7 digit TG's

### ISSUE THREAD

**Issue by ssoespre** [rogerclarkmelbourne/OpenGD77#649]
I tried to entry a new TGID / RID from the handheld, but it was limited only 7 digits, i still could write 8 digit TGID / RID from CPS and write to device, hoping this can be solved in the future.

**Comment by rogerclarkmelbourne** [comment]
Fixed by https://github.com/rogerclarkmelbourne/OpenGD77/commit/ea327a1b9469303cc8730ed9af2034113840dbeb

**Comment by ssoespre** [comment]
thankyou mate, cheers.
