### ISSUE TITLE
Double start of voice prompts when changing talkgroups (possibly only on L3)

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#654]
Double start of voice prompts when changing talkgroups (possibly only on L3)

Possibly also under other circumstances. 

Possibly prompts are being triggered on both button Down and Up events

**Comment by f1rmb** [comment]
Just tried this one, it looks fixed now.

**Comment by rogerclarkmelbourne** [comment]
Yes. I tested it as well, and could never replicate the problem that was reported on the forum

I think it was reported by a blind operator, so I'll ask Ian DJ0HF (who manages the package sent to the blind operators) as he may know what the problem actually is.

**Comment by rogerclarkmelbourne** [comment]
No one can reproduce this reported issue.
