### ISSUE TITLE
ShortUp function may not currently be furnctioning for buttons

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#657]
ShortUp function may not currently be functioning for buttons

**Comment by f1rmb** [comment]
Could you explain the problem, I don't understand it ;-)

**Comment by rogerclarkmelbourne** [comment]
Umm.

I think this was probably based on a bug report on the forum.

I can't remember the details, and it may be a false report.

I'll close the issue
