### ISSUE TITLE
Any chance for support for 2016 DM-5R models?

### ISSUE THREAD

**Issue by vkerkhoff-cl** [rogerclarkmelbourne/OpenGD77#667]
Hi, 

I have a really old 2016 model (Tier-I) DM-5. The screen and many things seem different from later DM-5Rs. Any chance this radio will ever be supported?

**Comment by rogerclarkmelbourne** [comment]
No. I doubt it.

The Tier2 version was created by https://github.com/ew1adg . You could ask him if he plans to make a version for the Tier 1 radio, but I'd be very surprised if anyone has the time to do this, for an obsolete radio
