### ISSUE TITLE
Shutdown code for the RD-5R may be unncessary

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#682]
The powerdown screen is probably unncessary on the RD-5R because it does not have any power down hardware.

The power to the whole radio is via a mechanical switch, hence its not possible to show a powerdown screen, so large portions of the powerdown screen could be #if'ed out of the RD-5R build

**Comment by f1rmb** [comment]
I'm not sure removing the poweroff menu deserve all the effort, as it should be removed from the menus structure and so on.
Maybe just removing the power switch pin checking is enough.

Cheers.
---
Daniel

**Comment by rogerclarkmelbourne** [comment]
Fixed by Daniel.....
