### ISSUE TITLE
[User Guide] PiStar RFLevel table has disappeared.

### ISSUE THREAD

**Issue by f1rmb** [rogerclarkmelbourne/OpenGD77#689]
The table added in commit 8687b64d16d2c857b2591992eac3953ddf49d567 is missing...

Power | PiStar RFLevel
--- | ---
50mW  | 1
250mW  | 5
500mW  |10
750mW  |15
1W  |  20
2W  | 40
4W  | 80
5W  | 99
5W++ | N/A

**Comment by rogerclarkmelbourne** [comment]
Fixed... In the development branch
