### ISSUE TITLE
Possible problem when changing channels that have different TG Lists attached

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#706]
https://www.opengd77.com/viewtopic.php?f=11&t=1

From nr0d

> My codeplug is attached. In the "Denver Area BM" zone, there is a repeater called "W0DMR Table Mtn", fourth and last in the list of channels. It has a TG list called "BM Table Mtn" applied to it. If I choose that zone on the radio and move to that channel, then scroll to the second TG in the list, which is "Table Mtn Local2", then hit UP or DOWN to move to another channel, the other channel shows the selected TG as "RMH Devil", which is the first in my list of contacts and is not applied to anything at all in this zone. It should never show up. Note that if I move off that "W0DMR Table Mtn" channel with the first TG in its list selected, this does not happen, only if I have one of the other three TGs in the list selected.
> 
> On the new channel which is showing "RMH Devil" as the TG (contact), I can hit LEFT or RIGHT to move to a TG that is actually in that channel's TG list, so this doesn't kill me - but I feel like it shouldn't happen.
> 
> I can produce a video demonstrating if needed. This is always repeatable.
> 
> Oh, and this is in the development version one release back - not the one released this week.

[tim1g77.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/5009357/tim1g77.zip)

**Comment by f1rmb** [comment]
PR raise #708

**Comment by rogerclarkmelbourne** [comment]
Fixed by PR 708... Thanks to Daniel.
