### ISSUE TITLE
During private the other stations callsign is not displayed in the QSO data unless its the contacts or DB

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#726]
I have not checked whether BM sends TA during private calls, but TA data (callsign) is not displayed during private calls

**Comment by f1rmb** [comment]
I just checked the code to be sure, so the LH list is already checked for data (TA) availability.

The only way is to use one OpenGD77 device as hotspot, as it fill the gap if TA is not available, by sending fake TA build from MMDVMHost QSO Info ;-)

Cheers.
...
Daniel
