### ISSUE TITLE
Motorboating noise on DMR transmissions

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#728]
Many radios now seem to have motorboating noise on their DMR transmission.

Not all radios seem to have this problem.

Changing display backlight intensity does not seem to make a difference, even if the display backlight is set to none or to 100%
Changing power level does not seem to make any difference.
Changing DMR Mic gain does not seem to make any difference.

Its unclear whether this is analogue noise, on the output of the ADC or whether this noise is being caused by the codec or possibly by some other process in the firmware.

Unfortunately none of my radios seem to exhibit this problem, so its hard for me to what is causing this

**Comment by alistairuk** [comment]
I have heard the transition of a GD-77 doing just this. It is almost the same as the sound created when a DMR RF signal causes interference on a hand held microphone. The sound generated would also fits the envelope of a DMR signal thought an analogue radio although perhaps less constant.

**Comment by DanNixon** [comment]
I have a GD77 that appears to be affected with this issue. I also find that none of the settings mentioned affect the noise.

I did suspect hardware issues for a while, but this now seems unlikely as the interference is not present when using the stock firmware.

I'd be happy to help try and find the cause of this as I am keen to keep using OpenGD77.

**Comment by rogerclarkmelbourne** [comment]
@DanNixon 

I think this problem may somehow have been introduced over the last month or two.

Can you try installing a much older version of the firmware e.g. the first of the "Releases"

You'll need to down the file from the "assets" in that release and then select that file in the firmware loader, rather than downloading the firmware directly from inside the loader

**Comment by rogerclarkmelbourne** [comment]
There was some speculation that this problem may be caused by the display dimming functionality, which the official firmware does not have.

Some people reported that turning back light intensity right down e..g just a few percent, gets rid of the noise, but I know someone else who has recently reported the problem, and he tried various intensity settings and I could not hear any difference in the motorboating on his transmission

For the DM-1801 version, I had to increase the PWM frequency used for the display dimming, because the original frequency I used was in the audible range, and it could be heard on either the DM-1801 Rx or Tx signal. (I can't remember which).

So I change the PWM frequency to 10kHz so its well outside audible range, and this resolved the problem on the DM-1801

I don't think this change coincided with the motorboating effect.


The only way to truely test if the problem is being caused by the backlight PWM, would be to make a special version which does not have dimmable backlight, or to change the code so that setting the backlight to Off or 100% or 0% would switch the backlight control to simple GPIO (General Purpose Input Output), which does not engage all the additional internal hardware in the MCU e.g. timers, used to generate the PWM

**Comment by rogerclarkmelbourne** [comment]
[OpenGD77_No_Backlight_Dimming.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/5242466/OpenGD77_No_Backlight_Dimming.zip)

Anyone who has the motorboating, please try this version which does not have backlight dimming and let me know if it resolves the problem

**Comment by DanNixon** [comment]
Ok, I might have to backtrack slightly from my initial report.

On the stable firmware (`e3b2b38`), the motorboating interference does seem somewhat proportional to the backlight setting:
- 0% not noticeable
- 10% not noticeable
- 20% barely noticeable
- 50% very noticeable
- 100% very noticeable

I gave the no backlight dimming firmware (`30bla54`) a go and found that unfortunately the problem was still there.

**Comment by rogerclarkmelbourne** [comment]
@DanNixon 

Please try the version I created and attached to my previous reply. I does not use PWM dimming.

However, those who tested this version, still reported motorboating, so I don't think that the PWM is the problem.

**Comment by DanNixon** [comment]
> Please try the version I created and attached to my previous reply. I does not use PWM dimming.

I have, it did not make any noticeable difference.

> However, those who tested this version, still reported motorboating, so I don't think that the PWM is the problem.

I agree, the noise is characteristic of a DMR transmission, however by some means it does look to be connected with the backlight control (I had a few ideas in my head, as did @alistairuk, but nothing conclusive).

2E0THD and I have also noted that there is some variation in the level of the noise after a power cycle and having been powered on for a length of time. e.g. I might be experiencing no noise, but immediately after a power cycle the noise returns (this was heard at low backlight levels where the noise was only marginal to begin with).

**Comment by rogerclarkmelbourne** [comment]
@DanNixon 

OK. That was the same feedback I got from someone else who tested the non-PWM

In which case the problem is not the PWM of the display backlight. It seems to be the additional current demand of the backlight LEDs which are effecting this.
Which is strange, as the backlight only takes around 20mA, and the overall Tx current is much higher than that, apart from the very low power settings.

When I get time I'll need to do some other test versions to try to isolate whether the noise is analogue or digital

**Comment by rogerclarkmelbourne** [comment]
[OpenGD77_DMR_Mic_analog_signal_mute.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/5250663/OpenGD77_DMR_Mic_analog_signal_mute.zip)

**Comment by rogerclarkmelbourne** [comment]
VKZCR just did  a test for me, and the noise is coming in on the analogue mic signal, as pressing the blue button stops the noise, as well as the mic audio

**Comment by DanNixon** [comment]
> Try this version. It will mute the DMR audio whilst the Blue button (SK2) is pressed during DMR trasnsmissions.

Yes, with this firmware there is no noise when the blue button is pressed.

**Comment by rogerclarkmelbourne** [comment]
Yep.

That's the results I got.

Unfortunately, it points to the problem being analog not digital, and its a mystery why the official firmware doesn't have this problem.

**Comment by rogerclarkmelbourne** [comment]
A fix for this has already been posted to the development update thread on the forum and the fix will be in the next public Beta release
