### ISSUE TITLE
editing channel names with voice prompts very difficult

### ISSUE THREAD

**Issue by vk7js** [rogerclarkmelbourne/OpenGD77#733]
When editing a channel name on the GD77 from the Channel Details menu, when you arrow left or right, enter new characters, or backspace, the entire display is reread. This makes it very difficult especially when arrowing over characters, to know where you are. Is it possible for you to:
1.	When new chars are entered, only read the new char just entered? If a user wants to hear the whole line they can press sk1.
2.	When a user backspaces out a char, the char being backspaced should be read.
3.	When a user arrows over a character, just the character being arrowed over should be read.
Right now, as things stand, it is very difficult for a blind person to edit a channel name. It is not impossible, but it is incredibly confusing. Particularly when arrowing over characters, you have no idea which char you are actually on.

Thanks for your consideration.

**Comment by rogerclarkmelbourne** [comment]
Fixed by vk7js
