### ISSUE TITLE
No audio sometimes on DMR when second person keys quickly behind first person on brandmeister

### ISSUE THREAD

**Issue by cjeffcoat2** [rogerclarkmelbourne/OpenGD77#735]
Hello, I have a GD 77 and a GD 77S. I discovered that on the GD 77, sometimes when someone keys quickly behind another person, I do not get audio, but the 77S does.￼￼

**Comment by f1rmb** [comment]
Is this still a valid, as I didn't experienced that bug ?

**Comment by rogerclarkmelbourne** [comment]
I have not tested it recently or noticed it.

So I'll close it.
