### ISSUE TITLE
VFO scan frequency entry Voice Prompt "point" not voiced for upper frequency

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#745]
Bug report from Ian DJ0HF

When voice prompts are enabled.

When entering the VFO scan frequency, the word "point" is voiced for the lower scan frequency, after the first 3 digits are entered, but "point" is not voiced when entering the upper scan frequency (after the third digit of the upper scan frequency is entered)

**Comment by f1rmb** [comment]
Fix in PR #748
