### ISSUE TITLE
All menu screens should replay the last Voice Prompt if SK1 is pressed

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#768]
The SK1 voice prompt functionality of replaying the last voice prompt should be added to all screens.
(There may be some screens where its not applicable)

I added the code to the Channel Details screen

See  ...   https://github.com/rogerclarkmelbourne/OpenGD77/commit/b8a1914260b2410e5ae61a1af89102c3b64cfc1d

But, its probably best to make this into a function in uiUtilities.c and call that functionfrom all the menu's (and probably the Channel and VFO mode screens, as I think the code may be identical)

**Comment by f1rmb** [comment]
On it ;-)

**Comment by rogerclarkmelbourne** [comment]
Thanks.
