### ISSUE TITLE
No way to set squelch to a non-custom squelch level

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#770]
If the internal squelch value is 0 (zero) on a Channel of the VFO, then the default squelch for that band (as defined in the Options) is used instead of the custom squelch.

However, AFIK at the moment once the user changes the squelch in the VFO (or potentially in a Channel), there is no way to return the squelch back to the default for the band.

I think perhaps the only way to implement a UI to change this to a non-custom squelch, would be to add a option to the Channel Details screen, either as a way of setting both the custom squelch value and changing to the squelch for the band, or possibly simply a way to switch between custom and band squelch.

**Comment by f1rmb** [comment]
Maybe KEY_LEFT && KEY_RIGHT could be used as a reset ?

**Comment by rogerclarkmelbourne** [comment]
We could just add another line in the Channel Details screen, below the Ch Power, because the functionality of the Channel squelch is the same as the Channel power.
I think this would be the most consistent thing to do.

**Comment by f1rmb** [comment]
Hi Roger,

  I think this one can be closed.

Cheers.
---
Daniel

**Comment by f1rmb** [comment]
Ping ;-)
