### ISSUE TITLE
No audio on GD Dash 77S

### ISSUE THREAD

**Issue by cjeffcoat2** [rogerclarkmelbourne/OpenGD77#779]
I loaded the latest firmware released today on my 77 and it works great with the latest voice pack. I uploaded the same release, the one released today on the 77S with the latest voice pack and there is no speech.￼

**Comment by cjeffcoat2** [comment]
OK, so I held down the button on the bottom left and turned on the radio and got speech back. Just something someone may want to take a look into.￼

**Comment by rogerclarkmelbourne** [comment]
Thanks

I will fix ASAP, but I'm at work at the moment.

**Comment by rogerclarkmelbourne** [comment]
Should be fixed now
