### ISSUE TITLE
Channel name seems to be announced on Voice level 3 when a DMR signal ends

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#787]
Channel name seems to be announced on Voice level 3 when a DMR signal ends

**Comment by f1rmb** [comment]
Hi Roger,

Humm, while scanning ? Because I just checked on normal operation, and I hear nothing.

Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
No. Not during scanning.

I think it announced just when a signal ended

**Comment by f1rmb** [comment]
Hi Roger,

I just tried while scaning, I don't noticed such problem.
Do you have a procedure to reproduce ?

Cheers.
...
Daniel

**Comment by f1rmb** [comment]
Hmmm, Ok.

**Comment by f1rmb** [comment]
I can only see a problem with loadChannelData(), being called when start RXing.

**Comment by rogerclarkmelbourne** [comment]
OK.

I will need to test, because I'm not sure under what conditions it occurred.

I just noticed that the radio was not scanning, and suddenly it announced the channel.

It may have rebooted, as I see that if I turn the radio off and on the channel is announced.

**Comment by f1rmb** [comment]
Yes, the channel name is announced while booting on L3

**Comment by rogerclarkmelbourne** [comment]
ummm

I can't replicate the bug again.

I will close the issue, because perhaps the problem is a random reboot.
