### ISSUE TITLE
Use extended memory in the DM-1801 for DMR IDs

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#789]
The DM-1801 has 2Mb Flash memory, instead of the 1Mb in the GD-77

This memory could be used to store the DMR ID database, and would increase the storage capacity by about 400%

This would require changes to both the firmware and also the CPS

**Comment by xcvista** [comment]
You may want to add a Flash capacity detection routine (most Flash chips have JEDEC information in it for this) so people with soldering skills can even upgrade that chip for even larger DMR ID database. For example I can put a 4Mb or 16Mb or 128Mb chip in there.
