### ISSUE TITLE
Power control no longer works on the GD77S since the update to the Channel power system

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#795]
GD77S code needs to be updated to use increasepower() and decreasepower()

**Comment by rogerclarkmelbourne** [comment]
This should now be fixed in the latest Development / Unstable firmware files

**Comment by cjeffcoat2** [comment]
OK, I realize this is you is closed, I went into modify some individual channel power settings and noticed that the power level is set to master, I modified this to what I would like for individual channels but now all of the rest of my channels have incorrect power levels, where is the master power level set?￼

**Comment by rogerclarkmelbourne** [comment]
It should be fixed 5 mins ago

**Comment by rogerclarkmelbourne** [comment]
Individual power settings on the GD77S is not currently supported

**Comment by cjeffcoat2** [comment]
OK, thank you so much I really appreciate all of the work that you are doing! It is fantastic and greatly appreciated.

**Comment by rogerclarkmelbourne** [comment]
You can add that as an enhancement issue, along with the other enhancement issues (lots of them)

**Comment by cjeffcoat2** [comment]
OK, sorry, posted this in the wrong spot it is for the 77.
