### ISSUE TITLE
Monitor mode for FM and DMR is required to check if a frequency is free before transmitting

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#804]
Work is already in progress for this feature

**Comment by vk7js** [comment]
I’m puzzled. I already implemented and tested this and created a pull request for this for both dmr and analog on a long hold of the orange button which was closed. You could have saved yourself some work.

It discourages anyone from contributing when this kind of thing happens.
