### ISSUE TITLE
Display something to indicate when a channel is marked as Scan Skip

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#809]
https://www.opengd77.com/viewtopic.php?f=4&t=997

**Comment by rogerclarkmelbourne** [comment]
I'm not sure how important this is, or when it would be useful.

**Comment by f1rmb** [comment]
I think that one can be closed too. IIRC, I tried few things, but in the end it was decided that it wasn't that useful and confusing.
