### ISSUE TITLE
Hotspot mode hang with PiStar showing radio is transmitting when it’s not

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#81]

**Comment by dh9yap** [comment]
I also have this mistake.

- Radio Retevis RT3

- Firmware 0.72

I'm just trying to change some settings.
Maybe it will work then.
If the error occurs it is not received from the Internet.
73 DH9YAP

**Comment by f1rmb** [comment]
should be fixed in #329

**Comment by rogerclarkmelbourne** [comment]
Fixed by Daniel.

Thanks
