### ISSUE TITLE
Possibly  auto detect DMR or FM signals in VFO scan mode

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#820]
Now that Monitor mode seems to reliably detect a DMR signal in less than around 125mS, it would be possible to make the VFO scan in a version of Monitor mode, which would then automatically switch to FM if the signal was not DMR

However the entire VFO scan system would probably need to be overhauled and partially re-written to do this.

**Comment by xcvista** [comment]
I’d say watch out for potential patent problem as this is treading close to the AMS feature on Yaesu System Fusion devices.
