### ISSUE TITLE
Аккумулятор

### ISSUE THREAD

**Issue by bigmavr** [rogerclarkmelbourne/OpenGD77#825]
При 25% заряда аккумулятора и работе только на приём, аккумулятор разрядился за 20 минут, издавая звук  при потере каждого процента. (DM-1801)
Заряженный аккумулятор от 100% до 25%  при работе только на приём, продержался около 24 часов.

**Comment by rogerclarkmelbourne** [comment]
1. Please translate your issues into English as no one working on the project speaks russian
2. Please read the open issues.  Power consumption is already listed in the known limitations
