### ISSUE TITLE
Low priority. Possibly display battery voltage instead of percentage

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#830]
Several people have requested that the battery voltage should be displayed instead of the percentage - this would need to be a display option

**Comment by f1rmb** [comment]
In the header ? Did they noticed the voltage is even more inaccurate than the percentage ? ;-)

**Comment by rogerclarkmelbourne** [comment]
Yes. I think they mean in the header.

Neither is accurate.

**Comment by rogerclarkmelbourne** [comment]
Fixed
