### ISSUE TITLE
Suggestion: change red button to cycle from channel mode to vfo a to vfo b to relieve orange button which brings up quick menu and is not intuitive to also switch vfo

### ISSUE THREAD

**Issue by vk7js** [rogerclarkmelbourne/OpenGD77#844]
Since the orange button is unreliable  on many models, and since switching between vfos and channel modes is probably more frequently done than using the orange button, I suggest changing the behaviour so that the red button cycles between channel mode, VFO a and VFO b, and keep orange button just for accessing the quick menu.

**Comment by f1rmb** [comment]
we're not going to change how the UI works about this, as it's well established since it was implemented, and we aren't breaking UX.
