### ISSUE TITLE
Scan channels screen design

### ISSUE THREAD

**Issue by da3020** [rogerclarkmelbourne/OpenGD77#861]
Suggestion: it would be great to represent the Channel scanning screen in the way to avoid unreadable blinking of scanning channels names and parameters.
It's better and enough to indicate somsing like "Scanning Zone xxx" and some progress indicator during scanning.

**Comment by vk7js** [comment]
Yes, and further to this, if you hit sk1, you hear the buzz of the channels and the voice prompt trying to announce the channel. It should just say scanning.

Thanks

Joe

**Comment by g4eml** [comment]
I don't agree with this suggestion. 
One of the major comments from users of other DMR radios is that they do not display the current channel when scanning. 
 
Displaying the changing channel names while scanning is a really useful feature and gives the user confidence that the scan is in progress on the expected channels.

**Comment by da3020** [comment]
Scan speed for analog and DMR channels is really different. With analog scan you really see nothing.

**Comment by rogerclarkmelbourne** [comment]
This idea was tested but the response from anyone who tested it, was that it was a retrograde step. So this will not be implemented
