### ISSUE TITLE
Correct guide.

### ISSUE THREAD

**Issue by da3020** [rogerclarkmelbourne/OpenGD77#863]
![Screenshot_20201122-101522_Chrome](https://user-images.githubusercontent.com/1008375/99897579-b903dd00-2cab-11eb-8615-2682f2820f9e.jpg)
Here is I correct frequency and note relation.

**Comment by apws** [comment]
well )), in case anybody interested, I converted guide to asciidoc(tor) format and rendered it with my tweaked theme for chrome extension; its readable down to 4inch mobile phone, I hope ... (hope I will put it on github soon too)
[201127 OpenGD77 _User Guide.m.pdf](https://github.com/rogerclarkmelbourne/OpenGD77/files/5660856/201127.OpenGD77._User.Guide.m.pdf)

**Comment by rogerclarkmelbourne** [comment]
I have now corrected that error
