### ISSUE TITLE
Plese document approx values for user power level e.g. 50mw, 750mw, ... 5w=4100??? 

### ISSUE THREAD

**Issue by vk7js** [rogerclarkmelbourne/OpenGD77#866]
Hi Roger,

Would you please document in the user power level section, what values approximately equate to what wattage for the builtin levels?
e.g. I assume 5w is around 4000, what about 50 mw? 500 MW? 750 MW? Etc? In order to intelligently use the new user power level, we need to know what values equate to the builtin levels.
I note that for example in the docs it says that you can have spurious emissions at 50 mw because the level is so low. What does that equate to in the user power levels, and would 100 MW be a better minimum value to use? if so, what does that equate to in the user power level setting?
Thanks
Joe

**Comment by rogerclarkmelbourne** [comment]
Not possible. 

The calibration data is individually tailored for each radio, output power for a specific PA drive value, vary considerably from radio to radio
