### ISSUE TITLE
TS2 not Displaying

### ISSUE THREAD

**Issue by VA3NDP** [rogerclarkmelbourne/OpenGD77#869]
RD-5r stops on active channel (during scan) that is set to TS2 and still displays TS1. The audio still comes through but it just doesn't display it. TS filter is ON as is CC filter.

**Comment by f1rmb** [comment]
Is it a DMR simplex channel ?

**Comment by VA3NDP** [comment]
No. It's a Repeater. I don't have any simplex Channels in my scan list. Thx

**Comment by rogerclarkmelbourne** [comment]
Enable 

Display Settings -> Info to show the TS and tell me whether the TS indication is in bold or inverse or a different font.

**Comment by VA3NDP** [comment]
"Inverse". 
I can change it manually per the instructions it just doesn't display TS 2 when it stops on a programmed channel using TS2. It works fine and it is picking up the correct TS but it just doesn't switch on the display. Thanks much !

**Comment by f1rmb** [comment]
Hi,

  If the TS is in inverse video, it means you turned the TS filtering off, that's why it stops on any TS1 or TS2 channel.

**Comment by VA3NDP** [comment]
Agreed. However, it doesn't change at anytime. Even when the TS filter is ON! That's why I was concerned. 
Cheers

**Comment by f1rmb** [comment]
It will never change, as Roger told you, the displayed TS is the TX one, not one detected on RX (when TS filtering is OFF)

**Comment by VA3NDP** [comment]
Yup. Got it. I was under the impression it was providing the "current incoming" TS. It's no problem if that's the way it was designed then it's perfect.

**Comment by f1rmb** [comment]
Okay ;-)

**Comment by rogerclarkmelbourne** [comment]
Closed as this is the normal operation of the firmware
