### ISSUE TITLE
Crash if all channels in a zone marked as "Zone Skip"

### ISSUE THREAD

**Issue by trengking** [rogerclarkmelbourne/OpenGD77#875]
apparently, when we try to scan at a zone which all channel were 'Zone Skip = Yes', the device is forced to restart.

i have this zone containing 3 channels, somewhat somehow, turns out i accidentally 'mark' them as zone skip channel. when i try to scan these channels, the device is restarted, later on i check on each channel and set it back to 'Zone Skip = No' and everything is back to normal.

can we get a message indicating that all channels are skipped rather than forced restart?

hope this is not a lot to ask, and of course, it is considered as low priority, TIA 😁👍

**Comment by rogerclarkmelbourne** [comment]
Fixed in the latest Beta release
