### ISSUE TITLE
Switching channel from active DMR frequency/talkgroup to active FM frequency causes green reception light to go out when it should continue to be lit

### ISSUE THREAD

**Issue by iPeaches** [rogerclarkmelbourne/OpenGD77#878]
Notably, when switching from active FM to active DMR, the light behaves as expected, going out for a short moment and then immediately lighting back up as the tuning completes. This bug also appears to occur even if the dmr frequency is not active, as shown in the attached video: https://photos.app.goo.gl/asEkUyCuoSEQPu2v5

**Comment by rogerclarkmelbourne** [comment]
OK.

I will confirm whether I can reproduce this problem

**Comment by rogerclarkmelbourne** [comment]
Should be fix in the latest release
