### ISSUE TITLE
follow-on not honoured with rxctcss/txctcss  announcement on channel details

### ISSUE THREAD

**Issue by vk7js** [rogerclarkmelbourne/OpenGD77#881]
Hi Roger/Daniel,

This was something I also fixed in the older firmware. Now that you've fixed the announcement of rxctcss and txctcss etc in the channel details screen in your latest pre-release, you can't arrow rapidly to change the number because rxctcss and txctcss is spoken prior to the number as you rapidly arrow. I had fixed this so only the number was spoken when rapidly arrowing. Please let us be a beta tester to catch these things. In summary, follow-on needs to be honoured to allow rapid and efficient changing of codes in the channel details screen especially because there are 104 dcs and 50+ css codes.
Thanks
Joe
vk7js

**Comment by f1rmb** [comment]
This has been changed in the latest beta.
Also, you can use SK2 + Left or Right, which jumps to the last/first CSS entry, then next/previous CSS type.

Cheers.

**Comment by vk7js** [comment]
Thanks for fixing this.

Joe
