### ISSUE TITLE
Pin code prompt

### ISSUE THREAD

**Issue by cjeffcoat2** [rogerclarkmelbourne/OpenGD77#882]
Just updated my GD77 to the latest firmware released today, I get a prompt for a pin code when I turn on the unit, I have never set one up before on the radio. I also have the latest voice prompts.￼

**Comment by rogerclarkmelbourne** [comment]
Load the latest CPS

https://github.com/rogerclarkmelbourne/OpenGD77CPS/releases/tag/R2020.12.13.01


and check the Boot screen -> Power on password enable

**Comment by cjeffcoat2** [comment]
Correct, it was my issue.￼
