### ISSUE TITLE
feature request: Enable Key Beep and Startup Sound seperately

### ISSUE THREAD

**Issue by DC7IA** [rogerclarkmelbourne/OpenGD77#889]
I really like that the radio can beep a call sign in morse code when turning it on, but I really don't like a tone when I press a key.

Maybe this could be a seperate setting. :D

Something like: 

`Startup Sound: yes/no`

That way the radio can be silent except for the startup sound.

**Comment by rogerclarkmelbourne** [comment]
There isn't space in the ROM for this sort of trivial feature.

Although the change may look simple, it requires a new menu item, which needs to be translated into 13 languages, it also needs a voice prompt data block, and we are getting critically short of space for many things.

What limited space we do have left in the program ROM etc, is now being prioritised for bug fixes and more important features like battery power saving and SMS etc.
