### ISSUE TITLE
codeplugChannelSaveDataForIndex corrupts frequencies

### ISSUE THREAD

**Issue by ajorg** [rogerclarkmelbourne/OpenGD77#89]
Channel details can be corrupted when saving to codeplug.

1. Set VFO to `146.96000MHz`
2. Copy to a channel using the `VFO --> Channel` quick setting
3. Save the channel to codeplug by triggering codeplugChannelSaveDataForIndex with function+GREEN in Channel details
4. Look at channel details again

Expected result:
Channel details should not change

Actual result:
TX and RX frequencies are offset or incomplete in some strange way. When using `146.96000MHz` I've seen it change to `46.96000MHz` and also `696.00000MHz`.

**Comment by rogerclarkmelbourne** [comment]
This has been fixed by @alexernst
