### ISSUE TITLE
Control of LED indicators

### ISSUE THREAD

**Issue by SP5QAD** [rogerclarkmelbourne/OpenGD77#897]
Hello,
In the original software it is possible to turn off / on the led indicator. Would it be possible also here (Open RD-5R) to make this option available? Or even better, the ability to adjust its brightness? In certain situations, especially at night, this would be very helpful.

73's Marcin.

**Comment by rogerclarkmelbourne** [comment]
https://github.com/rogerclarkmelbourne/OpenGD77/files/6072087/OpenGD77_20210303855.zip
