### ISSUE TITLE
Station not respond to a personal call then DMR Filter is TG or RxG

### ISSUE THREAD

**Issue by R6DJO** [rogerclarkmelbourne/OpenGD77#898]
The station does not respond to a personal call if the DMR Filter is set to reception of talkgroup or reception list.

**Comment by rogerclarkmelbourne** [comment]
Thanks

This does seem to be a bug.

I will be fixed

**Comment by rogerclarkmelbourne** [comment]
[OpenGD7_Fix#898.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/5961775/OpenGD7_Fix.898.zip)

**Comment by R6DJO** [comment]
Thanks, everything works fine now/

**Comment by rogerclarkmelbourne** [comment]
OK.

Note.
That version is my latest private build and also includes other bugs fixes for the "Motorboating" noise on DMR Tx, as well as the new "Eco Level" power saving feature, which will be automatically set to Level 1, which is a small amount of power saving when the radio is receiving and there is no signal.
