### ISSUE TITLE
Down arrow does not work after entering Options menu via QuickKey

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/OpenGD77#899]
Report on the forum

https://opengd77.com/viewtopic.php?f=11&t=1530

**Comment by f1rmb** [comment]
Hi Roger,

   I saw it on the forum, but completely forgot about it.
I will take a look at this today.

Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
OK. I've not confirmed the bug.

I can probably fix it at the weekend.

Currently I'm still in the middle of investigating the official firmware power saving

**Comment by f1rmb** [comment]
Okay. Well, I raised a PR for this one, so you can continue holding the probes ;-)

**Comment by rogerclarkmelbourne** [comment]
Thankyou.

Yes. I'm still holding the probes..

Actually, I'm running the official firmware with the JLink attached, and using GDB to make changes to the GPIO manually, without the official firmware noticing ;-)

**Comment by f1rmb** [comment]
LOL, just like a pickpocket.

**Comment by rogerclarkmelbourne** [comment]
[OpenGD77_Fix_#899.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/5970142/OpenGD77_Fix_.899.zip)
