### ISSUE TITLE
Python firmware loader not working

### ISSUE THREAD

**Issue by sm7tix** [rogerclarkmelbourne/OpenGD77#901]
stefan@stefan-MS-7681:~/OpenGD77/tools/Python/FirmwareLoader$ python3 gd-77_firmware_loader.py -m GD-77 -d U
 - Try to download the firmware for your GD-77 from the project page
 - Retrieve firmware location
Firmware download failed

Me or the file are wrong? :)
73 de SM7TIX / Stefan

**Comment by f1rmb** [comment]
Does it fail silently ?
Have you installed the dependencies (take a look at the beginning of the file ?
Have you installed the udev file ?

**Comment by sm7tix** [comment]
> Does it fail silently ?
> Have you installed the dependencies (take a look at the beginning of the file ?
> Have you installed the udev file ?

As you see in my text it stops with "Firmware download failed" 
It worked before, but today it didnt. So i clone the repo again but the same result. I think the modules are in place otherwise i have got a different error i think. The udev rules i dont think i have installed. I run as root so does it matter? Last time there was a new dev firmware i was able to download it.

**Comment by sm7tix** [comment]
All dependencies are in place

**Comment by f1rmb** [comment]
Hi,

 I just tried:

```
daniel@daniel-ThinkPad-X230:~ $ ./gd-77_firmware_loader.py -m GD-77 -d -U
 - Try to download the firmware for your GD-77 from the project page
 - Retrieve firmware location
 - Downloading the firmware version D2021.01.19.01, please wait
 - Now flashing your GD-77 with "/tmp/rmzeewph.sgl"
 - Firmware file confirmed as SGL
 - Sending Download command
 - Sending ACK
 - Sending encryption key
 - Sending F-PROG command
 - Sending radio modem number
 - Sending radio modem number 2
 - Sending version
 - Sending erase command
 - Send post erase command
 - Sending Program command
 - Sending last block                   
Firmware update complete. Please reboot the GD-77.
```

Your command line have a typo (as displayed, the dash is missing for the **U**.

**Comment by sm7tix** [comment]
OK! My fault. Working now. You can close it with a remark of a stupid user :)

**Comment by f1rmb** [comment]
Okay, cool.

**Comment by sm7tix** [comment]
Voice prompt not chooseble after upate. Do  i have to update voice prompt too? Is there a pythonscript for that too?

**Comment by f1rmb** [comment]
I think on the forum there is something.

**Comment by sm7tix** [comment]
Ok.

**Comment by rogerclarkmelbourne** [comment]
Does this issue need to stay open?

It appears to have been resolved

**Comment by f1rmb** [comment]
Yes, it can be closed.

**Comment by sm7tix** [comment]
Pls close

Den 13 februari 2021 22:23:50 skrev Roger Clark <notifications@github.com>:

**Comment by rogerclarkmelbourne** [comment]
I already closed it.

I think also you can close an issue if you opened it.

**Comment by sm7tix** [comment]
Ok!
Tnx.



Den 13 februari 2021 22:31:46 skrev Roger Clark <notifications@github.com>:
