### ISSUE TITLE
Voice prompt for FM

### ISSUE THREAD

**Issue by cjeffcoat2** [rogerclarkmelbourne/OpenGD77#903]
I've noticed on the main screen by pressing SK2 that the radio says mode FM, where FM appears to be a single file recording, but in the channel details screen, if you arrow down to mode, it says F M as in two individual letters, it sounds different and I was wondering if the firmware is calling two different recordings. If it could be made more consistent then perhaps one of the recordings could be deleted, just freeing up some memory space for another voice prompt￼

**Comment by rogerclarkmelbourne** [comment]
This just removes flexibility.

Originally we did use separate letters, but they played inconsistently depending on the language.

This would be a retrograde step and will not be implemented
