### ISSUE TITLE
Tone scan doesn't work when Filter is set to None #2

### ISSUE THREAD

**Issue by dmitrybabeshko** [rogerclarkmelbourne/OpenGD77#916]
Hello Roger,

This is a follow-up for #910 since the original has been closed.
The issue is still reproducible with the latest development release D2021.03.06.01 on DM-1801.

Thank you in advance.

**Comment by f1rmb** [comment]
Hi,

  It seems the fix hasn't been merged yet.

Thanks for the notice.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
Sorry.

Somehow that test branch didn't get merged back into my local main version.

I've merged it now into my local copy

[OpenGD77_20210307_fix_916.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/6096114/OpenGD77_20210307_fix_916.zip)

**Comment by dmitrybabeshko** [comment]
> I've merged it now into my local copy
> [OpenGD77_20210307_fix_916.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/6096114/OpenGD77_20210307_fix_916.zip)

Checked this build. Issue is fixed. Thank you.

**Comment by dmitrybabeshko** [comment]
Checked https://github.com/rogerclarkmelbourne/OpenGD77/releases/tag/D2021.03.21.01
Issue is resolved

**Comment by rogerclarkmelbourne** [comment]
OK
