### ISSUE TITLE
Development branch

### ISSUE THREAD

**Issue by on7lds** [rogerclarkmelbourne/OpenGD77#919]
I want to update the Dutch translations, but the development branch is missing ?
Or am I overlooking something ?

**Comment by f1rmb** [comment]
You need to use the master branch, the development one has been removed.

**Comment by on7lds** [comment]
* With that branch I do not seem to have the new menu's (radio info, temperature ...) ?
* I do the PR then to the master branch ?

**Comment by f1rmb** [comment]
The master has these entries. The only missing ATM are .buttons and .leds.
Yes, you should raise PR against master branch.

**Comment by on7lds** [comment]
Compiling the Github tree gives me the menu 'Battery' without the temperature.
Flashing the  (only possible choice) 'unstable' firmware with the OpenGD77CPS gives me the 'Radio info' menu with temperature.
What am I doing wrong ?

**Comment by rogerclarkmelbourne** [comment]
@on7lds 

The public repo does not contain the latest features.

It receives bug fixes and language updates but not major feature updates at the moment.

**Comment by on7lds** [comment]
Ah, OK.
Then I'll already just translate and wait for the functions to come in the master branch to verify if they fit (they should, but I like to verify).

note: README.md, still says to PR against the development branch.

**Comment by rogerclarkmelbourne** [comment]
Readme has now been updated
