### ISSUE TITLE
Feature request: RD-5R/DM-5R broadcast FM receiver

### ISSUE THREAD

**Issue by xcvista** [rogerclarkmelbourne/OpenGD77#924]
The DM-5R has a feature inherited from UV-5R: receiving FM broadcast. Can that feature be reinstated?

**Comment by rogerclarkmelbourne** [comment]
I have no technical data on the broadcast FM receiver chip.

See

https://github.com/rogerclarkmelbourne/OpenGD77/tree/master/docs/data_sheets/RDA5802E

Do you have a data sheet for the broadcast FM chip in this radio ?
