### ISSUE TITLE
Flashlight (LED) sk2+ 5 no longer working

### ISSUE THREAD

**Issue by VA3NDP** [rogerclarkmelbourne/OpenGD77#925]
RD-5R flashlight function no longer works when I push function button 2 + #5. Stopped working after last update. 
Current firmware- be33e68 
March 6, 2021

**Comment by rogerclarkmelbourne** [comment]
OK.
There were no specific changes to the buttons in the last update.,

The bug was probably introduced some time ago but remained unnoticed

**Comment by rogerclarkmelbourne** [comment]
Ah,

I wonder if this is something to do with the changes to the LEDs

**Comment by VA3NDP** [comment]
Quite possible. I rarely use it but I did notice it and thought I should note it. It's definitely not a big deal but I thought you would like to know. 
I did operate the new LED on/off function in the menu to see if that made a difference but no change.

**Comment by rogerclarkmelbourne** [comment]
I just tried my RD5R and the light is working fine.

Which version are you using ?

**Comment by VA3NDP** [comment]
Yup. Beta March 6

**Comment by rogerclarkmelbourne** [comment]
I just loaded that, and my RD5R LED still works as expected.

Which version still works OK for you ?

**Comment by VA3NDP** [comment]
The one directly ahead of that one was just fine. Instead of downgrading I can wait until the next release and see how it is? It's not the end of the world :)

**Comment by VA3NDP** [comment]
Did you want me to try a re-load or different version?

**Comment by VA3NDP** [comment]
I went back 5 firmwares and tried all of them with no luck. I'm thinking maybe my light is toast and I wasted your time? It's only 2 months old but it's possible ?? I can't wait until my 1801/860 arrives in a couple weeks 😉

**Comment by rogerclarkmelbourne** [comment]
Yep. Sounds like the LED packed up.

The RD5R hardware is junk really. Its only supported because some guy in Russia did the original conversion for the DM-5R V2.

But its been nothing but trouble ever since.

**Comment by rogerclarkmelbourne** [comment]
OK
