### ISSUE TITLE
Wrong text for current TimeSlot in the top row

### ISSUE THREAD

**Issue by grayhound56** [rogerclarkmelbourne/OpenGD77#934]
In DMR mode, the current TimeSlot in the top row is not shown as 'TS' but as 'cS'. Bug or feature?

**Comment by f1rmb** [comment]
No, it's not a typo. It's even documented, but I just noticed a typo in the manual about thsi.

cS means the contact is overriding the timeslot setting.

**Comment by grayhound56** [comment]
Thank you for the fast reaction. Can I close this?

**Comment by f1rmb** [comment]
yup ;-)
