### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by bardens** [rogerclarkmelbourne/OpenGD77#94]
- If the keys are pressed repeatedly, the menu appears sometimes. Maybe there helps a little delay?
- It would be helpful if a longer key press on the arrow keys can cause a repetition.

**Comment by rogerclarkmelbourne** [comment]
The keys need to be debounced.

I think this may already be an open issue

**Comment by alexernst** [comment]
I'm already started some work on this. 

Debounce, reapeat and some more is working. But it needs some polishing and testing.
I'll prepare a pull request in the next days even if it's not complete ready.

**Comment by rogerclarkmelbourne** [comment]
Alex
Thanks

I'll mark this as assigned to you, to stop anyone else starting the same work

**Comment by rogerclarkmelbourne** [comment]
Fixed by Alex
